steps:
- task: DotNetCoreCLI@2
  displayName: Build Engine Core
  inputs:
    command: build
    projects: FhirToCdm/*.sln
    arguments: '--configuration $(buildConfiguration)'

- task: NodeTool@0
  inputs:
    versionSpec: '12.x'
    checkLatest: true

- script: |
    npm install --prefix Configuration-Generator Configuration-Generator
    npm run build Configuration-Generator
  workingDirectory: FhirToCdm
  displayName: 'Install & Build Configuartion Generator'

- script: npm run citest --prefix Configuration-Generator
  workingDirectory: FhirToCdm
  displayName: 'Run Configuartion Generator Tests'

- task: DotNetCoreCLI@2
  displayName: Run Engine Core Tests
  inputs:
    command: test
    projects: '**/*Test/*.csproj'
    arguments: '--configuration $(buildConfiguration) --collect "Code coverage"'

- task: PublishTestResults@2
  displayName: Publish Test Results
  condition: succeededOrFailed()
  inputs:
    testRunner: JUnit
    testResultsFiles: '**/TEST-RESULTS.xml'